<a href="https://colab.research.google.com/github/N02468/Numpy.ipynb/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World");
print("My Name is Noman");

Hello World
My Name is Noman


In [ ]:
if 5 > 2:
    print("Five is greater than two");

Five is greater than two


In [1]:
from google.colab import files
upload= files.upload()

Saving joes-valentine-qyQJU0zKiXk-unsplash.jpg to joes-valentine-qyQJU0zKiXk-unsplash.jpg


In [ ]:
a=5
b=6
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

11
-1
30
0.8333333333333334
0
5
15625


In [ ]:
print("IF ELSE Statement")
a = 20
b = 30
if(a>b):
  print("a is greater than b")
else:
  print("b is greater than a")


IF ELSE Statement
b is greater than a


In [ ]:
list = ["apple","banana","cherry"]
print(list)

['apple', 'banana', 'cherry']


In [ ]:
from typing import Dict
Dict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}
print(Dict)
#

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [ ]:
function = lambda a: a + 10
print(function(5))

function = lambda a, b: a * b
print(function(5, 6))

cars = ["Ford", "Volvo", "BMW"]
cars.sort()
print(cars)

15
30
['BMW', 'Ford', 'Volvo']


In [ ]:
print("if Elif Statement")
a = 20
b = 30
if(a>b):
  print("a is greater than b")
elif(a==b):
  print("a is equal to b")
else:
  print("b is greater than a")

if Elif Statement
b is greater than a


**Import numpy as np**

In [10]:
import numpy as np
x=[1,2,3,4,5]
y=[6,7,8,9,10]
z=[11,12,13,14]
np.concatenate([x,y,z])


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Array**

In [11]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(y.ndim)

[1 2 3 4]
1


**Second Method**

In [12]:
x=[1,2,3,4]
y=np.array([1,2,3,4])
print(y)
print(y.ndim)

[1 2 3 4]
1


**How we know that this is Array**

In [14]:
x=[1,2,3,4]
y=np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [15]:
x=[1,2,3,4]
y=np.array([1,2,3,4])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [16]:
l = []
for i in range(1,5):
  int_1 = int(input("Enter: "))
  l.append(int_1)
print(np.array(l))
print(y.ndim)

Enter: 14
Enter: 15
Enter: 12
Enter: 13
[14 15 12 13]
1


***Q1:- How many types of Array are there ***

Answer:- There are four types of Array which are following:-



1, 1-D Array


2, 2-D Array


3, 3-D Array



4, Multidimensional Array

**2-D Array**

In [17]:
ar2 =np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2
